on:
  workflow_dispatch:
    inputs:
      host:
        description: 'IP of the target machine'
        required: true
      configuration:
        description: 'NixOS configuration to deploy'
        required: true

jobs:
  build:
    runs-on: "Proxmox 1"
    steps:
      - name: Rebuild vm
        run: |
          sudo nix run github:nix-community/nixos-anywhere -- --flake .#{{ github.event.inputs.configuration }} -i id_ed25519 --target-host builder@{{ github.event.inputs.host }} --generate-hardware-config nixos-generate-config ./hardware-configuration.nix