name: Install NixOS configuration

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'IP of the target machine'
        required: true
      configuration:
        description: 'NixOS configuration to deploy'
        required: true

jobs:
  build:
    runs-on: "nixos"
    steps:
      - uses: actions/checkout@v6
      - name: Add agamemnon to known hosts
        run: |
          ssh-keyscan ${{ github.event.inputs.host }} >> known_hosts
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > id_ed25519
          chmod 600 id_ed25519
      - name: Install to VM
        run: |
          nix run github:nix-community/nixos-anywhere -- --flake .#${{ github.event.inputs.configuration }} -o UserKnownHostsFile=known_hosts -i id_ed25519 builder@${{ github.event.inputs.host }}